### ISSUE TITLE
An issue loading the mod.

### ISSUE THREAD

**Issue by mrrainbowinc** [ustaalon/LethalCompany.LaserControl#5] opened 2024-02-11 19:59 UTC
I've tried 3 versions of the mod, 0.1.4,0.1.3 and 0.1.2, and none of them load properly. I am unsure what to do with this information. There is a strange error in the cmd box when launching lethal company but I have no idea what it means. (attached .txt file with text included). Please help. And thank you in advance.
`[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'LethalLib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
System.Reflection.RuntimeModule.ResolveMethod (System.Reflection.Module module, System.IntPtr monoModule, System.Int32 metadataToken, System.Type[] genericTypeArguments, System.Type[] genericMethodArguments) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Reflection.RuntimeModule.ResolveMethod (System.Int32 metadataToken, System.Type[] genericTypeArguments, System.Type[] genericMethodArguments) (at <787acc3c9a4c471ba7d971300105af24>:0)
MonoMod.Utils.DynamicMethodDefinition+<>c__DisplayClass3_0.<_CopyMethodToDefinition>g__ResolveTokenAs|1 (System.Int32 token, MonoMod.Utils.DynamicMethodDefinition+TokenResolutionMode resolveMode) (at <6733e342b5b549bba815373898724469>:0)
MonoMod.Utils.DynamicMethodDefinition+<>c__DisplayClass3_0.<_CopyMethodToDefinition>g__ReadOperand|0 (System.IO.BinaryReader reader, Mono.Cecil.Cil.Instruction instr) (at <6733e342b5b549bba815373898724469>:0)
MonoMod.Utils.DynamicMethodDefinition._CopyMethodToDefinition () (at <6733e342b5b549bba815373898724469>:0)
MonoMod.Utils.DynamicMethodDefinition.Reload () (at <6733e342b5b549bba815373898724469>:0)
MonoMod.Utils.DynamicMethodDefinition..ctor (System.Reflection.MethodBase method) (at <6733e342b5b549bba815373898724469>:0)
(wrapper dynamic-method) MonoMod.RuntimeDetour.ILHook+Context.DMD<MonoMod.RuntimeDetour.ILHook+Context::Refresh>(MonoMod.RuntimeDetour.ILHook/Context)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<MonoMod.RuntimeDetour.ILHook+Context::Refresh>?115230984(object)
HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.OnILChainRefresh (System.Object self) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
MonoMod.RuntimeDetour.ILHook.Apply () (at <4e2760c7517c4ea79c633d67e84b319f>:0)
HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo (System.Reflection.MethodBase replacement) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: IL Compile Error (unknown location)
HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo (System.Reflection.MethodBase replacement) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: IL Compile Error (unknown location)
HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.Patch (System.Reflection.MethodBase original, HarmonyLib.HarmonyMethod prefix, HarmonyLib.HarmonyMethod postfix, HarmonyLib.HarmonyMethod transpiler, HarmonyLib.HarmonyMethod finalizer, HarmonyLib.HarmonyMethod ilmanipulator) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
RuntimeNetcodeRPCValidator.NetcodeValidator.Patch (System.Reflection.MethodInfo rpcMethod, System.Boolean& isServerRpc, System.Boolean& isClientRpc) (at <0df0f351a5d94cbb9af1af6290fbdcfa>:0)
RuntimeNetcodeRPCValidator.NetcodeValidator.Patch (System.Type netBehaviourTyped) (at <0df0f351a5d94cbb9af1af6290fbdcfa>:0)
RuntimeNetcodeRPCValidator.NetcodeValidator.Patch (System.Reflection.Assembly assembly) (at <0df0f351a5d94cbb9af1af6290fbdcfa>:0)
RuntimeNetcodeRPCValidator.NetcodeValidator.PatchAll () (at <0df0f351a5d94cbb9af1af6290fbdcfa>:0)
Anubis.LC.LaserControlPlugin.LaserControlPlugin.Awake () (at <55d14a4fa8df44cdb4f4de7a12e14f3a>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.InputSystem.InputSystem:.cctor()`

**Comment by ustaalon** [comment] 2024-02-11 20:09
Hey @mrrainbowinc, how do you load the game? Could you let me know if you're using Thunderstore? From what I can understand from the log you shared here, the 'LethalLib' mod seems missing.

**Comment by mrrainbowinc** [comment] 2024-02-11 23:00
@ustaalon Sorry for not saying, I do have lethalLib installed. I'm still not sure why though.
![image_2024-02-11_180016318](https://github.com/ustaalon/LethalCompany.LaserControl/assets/159725926/0e8e2af2-a6cf-4e25-8e5b-6d755e7904fc)

**Comment by mrrainbowinc** [comment] 2024-02-11 23:01
Also obviously, I do use Thunderstore.

**Comment by ustaalon** [comment] 2024-02-12 00:28
Thanks, @mrrainbowinc, looking into it. Can you please share your profile code so I will be able to reproduce it?

**Comment by ustaalon** [comment] 2024-02-16 21:48
Hey @mrrainbowinc can you please share with me your profile sharing code so I will be able to reproduce it?

**Comment by ustaalon** [comment] 2024-02-24 13:05
Hey @mrrainbowinc I'm closing this till getting the profile sharing code. I could not reproduce it so far

**Closed as completed by ustaalon** 2024-02-24 13:05 UTC
Labels: bug, question
